portfolio/portfolio/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index_invité')->name('home');
Route::get('/home', 'HomeController@index_auth')->name('home');

Route::resource('projets', 'ProjetController');
Route::resource('articles', 'ArticleController');
Route::resource('messages', 'MessageController');
Route::resource('categories', 'CategorieController');
Route::resource('users', 'UserController');

portfolio/portfolio/app/Projets.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Projets extends Model
{
    use Notifiable;

    /*
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','description' ,'image_url', 'technology', 'repo_url', 'website_url', 'category_id'
    ];

    public function user()
    {
        return $this->belongsTo('App\Users');
    }

    public function categorie()
    {
        return $this->belongsTo('App\Categories');
    }
}

portfolio/portfolio/app/Http/Controllers/ProjetController.php
<?php

namespace App\Http\Controllers;

use App\Projets;
use App\Categories;
use Illuminate\Http\Request;

class ProjetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Projets::latest()->paginate(5);
  
        return view('projets.index',compact('projects'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categories::all();
        return view('projets.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $projects = Projets::create([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'image_url' => $request->input('image_url'),
            'technology' => $request->input('technology'),
            'repo_url' => $request->input('repo_url'),
            'website_url' => $request->input('website_url'),
            'category_id' => $request->input('category_id')
            
        ]);
        $projects->save();
   
        return redirect('/projets')->with('success', 'Le projet a été ajouté à la liste ! ');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $project = Projets::findOrFail($id);
        $category= Categories::all();
        return view('projets.show', compact('project','category'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = Projets::findOrFail($id);
        $categories = Categories::all();
        return view('projets.edit', compact('project','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $projects = Projets::whereId($id)->update([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'image_url' => $request->input('image_url'),
            'technology' => $request->input('technology'),
            'repo_url' => $request->input('repo_url'),
            'website_url' => $request->input('website_url'),
            'category_id' => $request->input('category_id')
            
        ]);
        // $projects->save();
        return redirect('/projets')->with('success', 'Le projet a été modifié avec succès !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Projets::findOrFail($id);
        $project->delete();

        return redirect('/projets')->with('info', 'Ce projet a bien été supprimé');
    }
}

portfolio/portfolio/resources/views/projets/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
  <div class="card-header">
    Ajouter un projet
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('projets.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Nom du projet:</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <div class="form-group">
              <label for="description">Description du projet :</label>
              <textarea rows="5" columns="5" class="form-control" name="description"></textarea>
          </div>
          <div class="form-group">
              <label for="image_url">URL de l'image souhaitée :</label>
              <input type="text" class="form-control" name="image_url" placeholder="Rentrez un lien issu d'un navigateur pour charger une image :)"/>
          </div>
          <div class="form-group">
            <label for="technology">Technologie principale du projet :</label>
            <input type="text" class="form-control" name="technology"/>
          </div>
          <div class="form-group">
            <label for="repo_url">URL du repo :</label>
            <input type="text" class="form-control" name="repo_url"/>
          </div>
          <div class="form-group">
            <label for="website_url">URL du site :</label>
            <input type="text" class="form-control" name="website_url"/>
          </div>
          <div class="form-group">
            <label for="category_id">Catégorie :</label>
            <select class="form-control" name="category_id">
            @foreach($categories as $category)
            <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
            </select>
        </div>
          <button type="submit" class="btn btn-primary">Add Data</button>
      </form>
  </div>
</div>
@endsection

portfolio/portfolio/resources/views/projets/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
  <div class="card-header">
    Ajouter un projet
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('projets.update', $project->id ) }}">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="name">Nom du projet:</label>
          <input type="text" class="form-control" name="name" value="{{$project->name}}"/>
          </div>
          <div class="form-group">
              <label for="description">Description du projet :</label>
              <textarea rows="5" columns="5" class="form-control" name="description">{{$project->description}}</textarea>
          </div>
          <div class="form-group">
              <label for="image_url">URL de l'image souhaitée :</label>
              <input type="text" class="form-control" name="image_url" placeholder="Rentrez un lien issu d'un navigateur pour charger une image :)" value="{{$project->image_url}}"/>
          </div>
          <div class="form-group">
            <label for="technology">Technologie principale du projet :</label>
            <input type="text" class="form-control" name="technology" value="{{$project->technology}}"/>
          </div>
          <div class="form-group">
            <label for="repo_url">URL du repo :</label>
            <input type="text" class="form-control" name="repo_url" value="{{$project->repo_url}}"/>
          </div>
          <div class="form-group">
            <label for="website_url">URL du site :</label>
            <input type="text" class="form-control" name="website_url" value="{{$project->website_url}}"/>
          </div>
          <div class="form-group">
            <label for="category_id">Catégorie :</label>
            <select class="form-control" name="category_id">
            @foreach($categories as $category)
            <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
            </select>
        </div>
          <button type="submit" class="btn btn-primary">Modifier le projet</button>
      </form>
  </div>
</div>
@endsection

portfolio/portfolio/resources/views/projets/index.blade.php
@extends('layouts.app')

@section('content')
@auth
<a class="btn btn-success" href="{{ route('projets.create') }}"><i class="fas fa-plus-circle">Ajouter</i></a>
@endauth
<div class="container">
  <div class="row">
    @foreach ($projects as $project)
    <div class="col">
      <div class="card" style="width: 18rem;">
        <img src="{{$project->image_url}}" class="card-img-top" alt="{{$project->name}}">
          <div class="card-body">
            <h5 class="card-title">{{$project->name}}</h5>
            <p class="card-text">{{ Illuminate\Support\Str::limit($project->description, 350, $end='[......]') }}</p>
            <a href="{{ route('projets.show',$project->id) }}" class="btn btn-primary">Voir +</a>
              @auth
              <a href="{{ route('projets.edit', $project->id)}}" class="btn btn-warning"><i class="fas fa-edit"></i></a>
              <form action="{{ route('projets.destroy', $project->id)}}" method="post">
                @csrf
                @method('DELETE')
                <a><button class="btn btn-danger" type="submit"><i class="fas fa-trash"></i></button></a>
              </form>
              @endauth
          </div>
      </div>
    </div>
    @endforeach

  </div>
</div>
{!! $projects->links() !!}
@endsection

portfolio/portfolio/resources/views/projets/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="p-3 mb-2 bg-dark text-white">
        <img class='img-fluid rounded-circle' src="{{$project->image_url}}" alt="{{$project->name}}">
        <p>Nom : {{$project->name}}</p>
        <p>Description brève du projet : {{$project->description}}</p>
        <p>Technologie principale du projet : {{$project->technology}}</p>
        @if($project->repo_url == '' || $project->repo_url === NULL)
        <p>Il n'y a aucun repo pour ce projet</p>
        @else 
        <p>Repo git du projet : <a href="{{$project->repo_url}}">{{$project->repo_url}}</a></p>
        @endif
        @if($project->website_url == '' || $project->website_url === NULL )
        <p>Il n'y a aucun URL pour ce projet</p>
        @else 
        <p>URL du projet : <a href="{{$project->website_url}}">{{$project->website_url}}</a></p>
        @endif
        @foreach ($category as $cat)
            @if($project->category_id == $cat->id)
                <span class="badge badge-info">{{$cat->name}}</span>
            @endif
        @endforeach
        </div>
    </div>
</div>
@endsection