portfolio/portfolio/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index_invité')->name('home');
Route::get('/home', 'HomeController@index_auth')->name('home');

Route::resource('projets', 'ProjetController');
Route::resource('articles', 'ArticleController');
Route::resource('messages', 'MessageController');
Route::resource('categories', 'CategorieController');
Route::resource('users', 'UserController');

portfolio/portfolio/resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
  <div class="card-header">
    Créer une catégorie
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('categories.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Nom de la catégorie :</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <div class="form-group">
             <label for="slug">Slug :</label>
             <input type="name" name="slug">
          </div>
          <button type="submit" class="btn btn-primary">Créer catégorie</button>
      </form>
  </div>
</div>
@endsection

portfolio/portfolio/resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
  <div class="card-header">
    Modifier la catégorie
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('categories.update', $categorie->id ) }}">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="name">Nom de la catégorie :</label>
          <input type="text" class="form-control" name="name" value="{{$categorie->name}}"/>
          </div>
          <div class="form-group">
              <label for="slug">Slug :</label>
          <input type="text" name="slug" value="{{$categorie->slug}}">
          </div>
          <button type="submit" class="btn btn-primary">Modifier cette catégorie</button>
      </form>
  </div>
</div>
@endsection

portfolio/portfolio/resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
@auth 

<a class="btn btn-success" href="{{ route('categories.create') }}"><i class="fas fa-plus-circle">Ajouter catégorie</i></a>
<h2>Liste des catégories: </h2>
<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Nom</th>
        <th>Slug</th>
        <th>Action</th>
    </tr>
    @foreach ($categories as $categorie)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $categorie->name }}</td>
        <td>{{ $categorie->slug }}</td>
        <td>
            <form action="{{ route('messages.destroy',$categorie->id) }}" method="POST">

                <a class="btn btn-info" href="{{ route('messages.show',$categorie->id) }}">Voir</a>

                <a class="btn btn-warning" href="{{ route('messages.edit',$categorie->id) }}">Editer</a>

                @csrf
                @method('DELETE')
  
                <button type="submit" class="btn btn-danger">Suppr.</button>
            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $categories->links() !!}
@endauth
@endsection

portfolio/portfolio/resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="d-flex justify-content-center">
        <div class="p-3 mb-2 bg-dark text-white">
        <p>Nom : {{$categorie->name}}</p>
        <br>
        <p>Email de l'expéditeur : {{$categorie->slug}}</p>
    </div>
</div>
@endsection